---
name: "Nix build"
on:
  pull_request:
  push:
  workflow_call:
jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v10
    - uses: cachix/cachix-action@v12
      with:
        name: neorocks
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix flake check -L --accept-flake-config
  build-devShell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@v10
    - uses: cachix/cachix-action@v12
      with:
        name: neorocks
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#devShells.x86_64-linux.default -L --accept-flake-config 
